# Default values for bankapp.
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: "amitabhdevops/devsecops-bankapp"  # Your Docker Hub repo URI
  pullPolicy: IfNotPresent
  tag: "f48c2bef27d9fbcc546399a79f0dd11610ff65df"

service:
  type: ClusterIP
  port: 8080

database:
  host: "db-service"
  port: 3306
  name: "bankapp"
  user: "bankuser"
  password: "" # To be provided from Secrets

ollama:
  url: "http://172.17.0.1:11434" # Docker bridge IP for reaching host container

gateway:
  name: "bankapp-gateway"
  className: "envoy" # Envoy Gateway Controller
  host: "18.206.95.119.nip.io"
  envoyProxy:
    name: "bankapp-proxy-config"
    serviceType: NodePort
    nodePorts:
      http: 30080
      https: 30443
  tls:
    enabled: true
    secretName: "bankapp-tls"
    certManager:
      enabled: true
      issuerName: "letsencrypt-prod"
      email: "amitabhdevops2004@gmail.com"

nginx:
  enabled: true
  image: nginx:latest
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
