# Default values for bankapp.
# This is a YAML-formatted file.

replicaCount: 1

domain: "bankapp.amitabh.cloud"

image:
  repository: "981526069311.dkr.ecr.us-east-1.amazonaws.com/devsecops-bankapp"  # Your ECR repo URI
  pullPolicy: IfNotPresent
  tag: "5ba631e8bd1218f02e8c8f76588931fe0b41ff4b"

service:
  type: ClusterIP
  port: 8080

database:
  host: "db-service"
  port: 3306
  name: "bankapp"
  user: "bankuser"
  password: "" # To be provided from Secrets

ollama:
  url: "http://172.31.43.184:11434" # Replace with real Private IP

gateway:
  name: "bankapp-gateway"
  className: "envoy" # Envoy Gateway Controller

nginx:
  enabled: true
  image: nginx:latest
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
