apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: bankapp-proxy-config
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    kubernetes:
      envoyService:
        ports:
          - name: http
            nodePort: 30080
            port: 80
            protocol: TCP
          - name: https
            nodePort: 30443
            port: 443
            protocol: TCP
        type: NodePort
    type: Kubernetes