apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: bankapp-proxy-config
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        name: bankapp-envoy
        type: NodePort
        ports:
          - name: http
            port: 80
            nodePort: 30080
          - name: https
            port: 443
            nodePort: 30443